linters:
  enable:
    - govet
    - revive
    - unused
    - typecheck
    - staticcheck

  disable:
    - misspell
    - depguard

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - lll

  max-same-issues: 10

run:
  timeout: 2m

min-linters-count: 3
